version: '3.4'

services:
  postgres:
    container_name: threads-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgesql/data
    environment:
      POSTRGES_USER: postgres
      POSTRGES_DB: threads
      POSTGRES_PASSWORD: threads

volumes:
  postgres_data: